Repository Corvusoft/restbed, pull requests merged in 2021-01, with the labels that each got.

#448 Fix an inferable null pointer dereference on a smart pointer
  source/corvusoft/restbed/http.cpp
Labels: bug

#443 Fix and optimize URI codec.
  source/corvusoft/restbed/uri.cpp
Labels: enhancement

#434 windows dll exports
  CMakeLists.txt
  source/corvusoft/restbed/context_placeholder.hpp
  source/corvusoft/restbed/context_placeholder_base.hpp
  source/corvusoft/restbed/context_value.hpp
  source/corvusoft/restbed/http.hpp
  source/corvusoft/restbed/logger.hpp
  source/corvusoft/restbed/request.hpp
  source/corvusoft/restbed/resource.hpp
  source/corvusoft/restbed/response.hpp
  source/corvusoft/restbed/rule.hpp
  source/corvusoft/restbed/service.hpp
  source/corvusoft/restbed/session.hpp
  source/corvusoft/restbed/session_manager.hpp
  source/corvusoft/restbed/settings.hpp
  source/corvusoft/restbed/ssl_settings.hpp
  source/corvusoft/restbed/string.hpp
  source/corvusoft/restbed/uri.hpp
  source/corvusoft/restbed/web_socket.hpp
  source/corvusoft/restbed/web_socket_message.hpp
Labels: build issue

#447 Added cmake targets in cmake file so that restbed can be used from another cmake project
  CMakeLists.txt
  cmake/RestbedConfig.cmake.in
Labels: build issue

#458 Revert "Added cmake targets in cmake file so that restbed can be used from another cmake project"
  CMakeLists.txt
  cmake/RestbedConfig.cmake.in
Labels: build issue
